{% set version = "0.2.1" %}
{% set name = "python-syringe-pump" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ddedalus/syringe-pump/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b89eeebd0ad89a2e54c3f8af2e75087d6da6299dbe885df786594b4903c5758

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - poetry-core

  run:
    - python >=3.10
    - pydantic >=2.0.0
    - aioserial >=1.3.1
    - quantiphy >=2.19

test:
  imports:
    - syringe_pump

about:
  home: https://github.com/Ddedalus/syringe-pump
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: Controller for a Legato 100 syringe pump, commonly used in flow chemistry experiments
  dev_url: https://github.com/Ddedalus/syringe-pump

extra:
  recipe-maintainers:
    - beenje
    - JEOOOL
